backbone:
- - -1
  - 1
  - Conv
  - - 64
    - 3
    - 2
- - -1
  - 1
  - Conv
  - - 96
    - 3
    - 2
- - -1
  - 3
  - C2f
  - - 96
    - true
- - -1
  - 1
  - Conv
  - - 192
    - 3
    - 2
- - -1
  - 6
  - C2f
  - - 192
    - true
- - -1
  - 1
  - Conv
  - - 384
    - 3
    - 2
- - -1
  - 6
  - C2f
  - - 384
    - true
- - -1
  - 1
  - Conv
  - - 768
    - 3
    - 2
- - -1
  - 3
  - C2f
  - - 768
    - true
- - -1
  - 1
  - SPPF
  - - 768
    - 5
ch: 3
depth_multiple: 0.67
head:
- - -1
  - 1
  - nn.Upsample
  - - None
    - 2
    - nearest
- - - -1
    - 6
  - 1
  - Concat
  - - 1
- - -1
  - 3
  - C2f
  - - 384
- - -1
  - 1
  - nn.Upsample
  - - None
    - 2
    - nearest
- - - -1
    - 4
  - 1
  - Concat
  - - 1
- - -1
  - 3
  - C2f
  - - 192
- - -1
  - 1
  - Conv
  - - 256
    - 3
    - 2
- - - -1
    - 12
  - 1
  - Concat
  - - 1
- - -1
  - 3
  - C2f
  - - 384
- - -1
  - 1
  - Conv
  - - 512
    - 3
    - 2
- - - -1
    - 9
  - 1
  - Concat
  - - 1
- - -1
  - 3
  - C2f
  - - 576
- - - 15
    - 18
    - 21
  - 1
  - Detect
  - - nc
nc: 1
width_multiple: 0.75
